feat(sysv init): Add support for EL6 and SLES11 (#1507)
* Rewritten service file from scratch to account for both RHEL6 and SLES11

* Rearrange order of status so it works correctly on SuSE

* Remove usage of SuSE's recommended startproc, and launch manually

* Make final SuSE compatible changes

* Add LSB headers to service file

* Supporting SysV init via the install script

* Make sed regexp-extended argument more cross platform

* Move environment variables from service file to sysconfig file, where they belong

* Add packaging support for the sysv init file

* Fix incorrect destination for the sysconfig file in the archives

* Remove unneeded exports

* Fixing extraneous information added from copy/paste per PR feedback

* Addressing shellcheck issues

* Additionally corrections for shellcheck recommendations

* Add SysV support to the updater

* Add missing function comments for the new functions

* Update existing tests to pass

* Fix updater error message

* SysV startup script, truncate pidfile on start and add timeout to stop

* Add missing quotes to make shellcheck happy

* Address PR feedback for handling the actual service definitions. Move path components to proper file.

* Remove unneeded error return type

* Update updater linux service tests to be for systemd directly

* Address Joe's experience with starting already running service nuking the pid

* Final (hopefully) pass at integration tests

* Remove old service testing file

* Forgotten _sysv append on go build line for test

* Fix order, and parameter, for EL6 timeout for stop

* Switch to const defines for the service file paths. Remove service name variable usage

* Resolve linter issues

* Update Linux service tests to account for struct changes

* Swallow service commands output in the install script

* Add missing space in echo commands inside the service file

* Implement cleaner LinuxServiceFilePath() code suggestion

Co-authored-by: Brandon Johnson <brandon.johnson@bluemedora.com>

* Correct order of chkconfig command exec

* Fix formatting

* fix unit tests

* Add missing newlines to service start, stop, and status commands

* Fix shellcheck issues and systemctl failure in the unix install script

* Implement the suggestion of abusing case statement to become POSIX compatible

* Add a 1 second sleep to prevent the odd failures of restart

---------

Co-authored-by: Brandon Johnson <brandon.johnson@bluemedora.com>
Co-authored-by: Brandon Johnson <brandon.johnson@observiq.com>

diff --git a/service/observiq-otel-collector b/service/observiq-otel-collector
--- a/service/observiq-otel-collector
+++ b/service/observiq-otel-collector
@@ -5,120 +5,244 @@
 # processname: observiq-otel-collector
 # pidfile: /var/run/observiq-otel-collector.pid
 
+### BEGIN INIT INFO
+# Provides: observiq-otel-collector
+# Required-Start: 
+# Required-Stop: 
+# Should-Start: 
+# Default-Start: 3 5
+# Default-Stop: 0 1 2 6  
+# Description: Start the observiq-otel-collector service
+### END INIT INFO
+
 # Source function library.
+# RHEL
 if [ -e /etc/init.d/functions ]; then
   STATUS=true
+  # shellcheck disable=SC1091
   . /etc/init.d/functions
 fi
+# SUSE
+if [ -e /etc/rc.status ]; then
+  RCSTATUS=true
+  # Shell functions sourced from /etc/rc.status:
+  #      rc_check         check and set local and overall rc status
+  #      rc_status        check and set local and overall rc status
+  #      rc_status -v     ditto but be verbose in local rc status
+  #      rc_status -v -r  ditto and clear the local rc status
+  #      rc_failed        set local and overall rc status to failed
+  #      rc_failed <num>  set local and overall rc status to <num><num>
+  #      rc_reset         clear local rc status (overall remains)
+  #      rc_exit          exit appropriate to overall rc status
+  # shellcheck disable=SC1091
+  . /etc/rc.status
 
+  # First reset status of this service
+  rc_reset
+fi
+# LSB Capable
 if [ -e /lib/lsb/init-functions ]; then
   PROC=true
+  # shellcheck disable=SC1091
   . /lib/lsb/init-functions
 fi
 
+# Return values acc. to LSB for all commands but status:
+# 0 - success
+# 1 - generic or unspecified error
+# 2 - invalid or excess argument(s)
+# 3 - unimplemented feature (e.g. "reload")
+# 4 - insufficient privilege
+# 5 - program is not installed
+# 6 - program is not configured
+# 7 - program is not running
+#
+# Note that, for LSB, starting an already running service, stopping
+# or restarting a not-running service as well as the restart
+# with force-reload (in case signalling is not supported) are
+# considered a success.
+
 # Pull in sysconfig settings
+# shellcheck disable=SC1091
 [ -f /etc/sysconfig/observiq-otel-collector ] && . /etc/sysconfig/observiq-otel-collector
 
-PROGRAM=observiq-otel-collector
-LOCKFILE=/var/lock/$PROGRAM
-OIQ_OTEL_COLLECTOR_HOME=/opt/observiq-otel-collector
-OIQ_OTEL_COLLECTOR_STORAGE=/opt/observiq-otel-collector/storage
-HTTP_PROXY=
-HTTPS_PROXY=
-# set this to a user such as observiq-otel-collector, to run as that user
-# observiq-otel-collector user is created during installation
-# leave this variable empty to run as root (Default behavior)
-RUNUSER=
-PIDFILE=/var/run/observiq-otel-collector.pid
-DEBUG=false
 RETVAL=0
 start() {
-  if [ -f $PIDFILE ]; then
-    PID=$(cat $PIDFILE)
-    echo " * $PROGRAM already running: $PID"
-    RETVAL=2
-  else
-    echo " * Starting $PROGRAM"
-    if [ $DEBUG ]; then
-      COMMAND="cd /opt/observiq-otel-collector/ && nohup /opt/observiq-otel-collector/observiq-otel-collector --config config.yaml 1> /dev/null 2>> $OIQ_OTEL_COLLECTOR_HOME/log/error.log"
-    else
-      COMMAND="cd /opt/observiq-otel-collector/ && nohup /opt/observiq-otel-collector/observiq-otel-collector --config config.yaml 1>> $OIQ_OTEL_COLLECTOR_HOME/log/error.log 2>&1"
-    fi
-    export OIQ_OTEL_COLLECTOR_HOME
-    export OIQ_OTEL_COLLECTOR_STORAGE
-    export HTTP_PROXY
-    export HTTPS_PROXY
-    if [ -n "$RUNUSER" ]; then
-      su -p "$RUNUSER" -c "$COMMAND" &
-    else
-      nohup "$COMMAND" &
-    fi
-    echo $! > $PIDFILE
-    # disabling shellcheck due to this being the one documented exception. See https://www.shellcheck.net/wiki/SC2320
-    # shellcheck disable=SC2320
+  [ -x "$PROGRAM" ] || exit 5
+
+  # shellcheck disable=SC3037
+  echo -n "Starting $0: "
+
+  # RHEL
+  if [ "$STATUS" ]; then
+    umask 077
+
+    daemon --pidfile="$PIDFILE" "$START_CMD"
     RETVAL=$?
-    [ "$RETVAL" -eq 0 ] && touch $LOCKFILE
+    # truncate the pid file, just in case
+    : > "$PIDFILE"
+    # shellcheck disable=SC2005
+    echo "$(pidof "$BINARY")" > "$PIDFILE"
+    [ "$RETVAL" -eq 0 ] && touch "$LOCKFILE"
+  # SUSE
+  elif [ "$RCSTATUS" ]; then
+    ## Start daemon with startproc(8). If this fails
+    ## the echo return value is set appropriate.
+
+    # NOTE: startproc return 0, even if service is
+    # already running to match LSB spec.
+    nohup "$PROGRAM" --config config.yaml > /dev/null 2>&1 &
+
+    # Remember status and be verbose
+    rc_status -v
+
+    # truncate the pid file, just in case
+    : > "$PIDFILE"
+    # shellcheck disable=SC2005
+    echo "$(pidof "$BINARY")" > "$PIDFILE"
   fi
+  echo
 }
 
 stop() {
-  if [ -f $PIDFILE ]; then
-    PID=$(cat $PIDFILE);
-    printf " * Stopping %s... " "$PROGRAM"
-    kill "$PID" > /dev/null 2>&1
-    echo "stopped"
-    rm $PIDFILE && rm -f $LOCKFILE
-    RETVAL=0
-  else
-    echo " * $PROGRAM is not running"
-    RETVAL=3
+  # shellcheck disable=SC3037
+  echo -n "Shutting down $0: "
+  # RHEL
+  if [ "$STATUS" ]; then
+      killproc -p "$PIDFILE" -d30 "$BINARY"
+      RETVAL=$?
+      echo
+      [ "$RETVAL" -eq 0 ] && rm -f "$LOCKFILE"
+      return "$RETVAL"
+  # SUSE
+  elif [ "$RCSTATUS" ]; then
+      ## Stop daemon with killproc(8) and if this fails
+      ## set echo the echo return value.
+      killproc -t30 -p "$PIDFILE" "$BINARY"
+
+      # Remember status and be verbose
+      rc_status -v
   fi
+  echo
+}
+
+# Currently unimplemented
+reload() {
+  # RHEL
+  #if [ $STATUS ]; then
+  # SUSE
+  #elif [ $RCSTATUS ]; then
+  #fi
+  echo "Reload is not currently implemented for $0"
+  RETVAL=3
+}
+
+# Currently unimplemented
+force_reload() {
+  # RHEL
+  #if [ $STATUS ]; then
+  # SUSE
+  #elif [ $RCSTATUS ]; then
+  #fi
+  echo "Reload is not currently implemented for $0, redirecting to restart"
+  restart
+}
+
+pid_not_running() {
+  echo " * $PROGRAM is not running"
+  RETVAL=7
 }
 
 pid_status() {
   if [ -e "$PIDFILE" ]; then
-    # disabling this shellcheck due to needing legacy support on some systems
-    # shellcheck disable=SC2006
-    # disabling this shellcheck due to incorrect detection
-    # shellcheck disable=SC2046
-    echo " * $PROGRAM" is running, pid=`cat "$PIDFILE"`
-    RETVAL=0
+    if ps -p "$(cat "$PIDFILE")" > /dev/null; then
+      echo " * $PROGRAM" is running, pid="$(cat "$PIDFILE")"
+    else
+      pid_not_running
+    fi
   else
-    echo " * $PROGRAM is not running"
-    RETVAL=1
+    pid_not_running
   fi
 }
 
 otel_status() {
-  if [ "$PROC" ]; then
-    status_of_proc -p $PIDFILE "$PROGRAM" "$PROGRAM"
+  if [ -e "$PIDFILE" ]; then
+    # shellcheck disable=SC3037
+    echo -n "Status of $0 ($(cat "$PIDFILE")) "
+  else
+    # shellcheck disable=SC3037
+    echo -n "Status of $0 (no pidfile found) "
+  fi
+
+  if [ "$STATUS" ]; then
+    status -p "$PIDFILE" "$PROGRAM"
     RETVAL=$?
-  elif [ "$STATUS" ]; then
-    status -p $PIDFILE $PROGRAM
+  elif [ "$RCSTATUS" ]; then
+    ## Check status with checkproc(8), if process is running
+    ## checkproc will return with exit status 0.
+
+    # Status has a slightly different for the status command:
+    # 0 - service running
+    # 1 - service dead, but /var/run/  pid  file exists
+    # 2 - service dead, but /var/lock/ lock file exists
+    # 3 - service not running
+
+    # NOTE: checkproc returns LSB compliant status values.
+    checkproc -p "$PIDFILE" "$PROGRAM"
+    rc_status -v
+  elif [ "$PROC" ]; then
+    status_of_proc -p "$PIDFILE" "$PROGRAM" "$PROGRAM"
     RETVAL=$?
   else
     pid_status
   fi
+  echo
 }
 
+cd "$OIQ_OTEL_COLLECTOR_HOME" || exit 1
 case "$1" in
+  # Start the service
   start)
     start
     ;;
+  # Stop the service
   stop)
     stop
     ;;
+  # Get the status of the service
   status)
     otel_status
     ;;
+  # Restart the service by stop, then restart
   restart)
     stop
+    # sleep for 1 second to prevent false starts leaving us in a bad state
+    sleep 1
     start
     ;;
+  # Not currently implemented, but should reload the config file
+  reload)
+    reload
+    ;;
+  # Not currently implemented, but should reload the config file.
+  # If it fails, restart
+  force-reload)
+    force_reload
+    ;;
+  # Conditionally restart the service (only if running already)
+  condrestart|try-restart)
+    otel_status >/dev/null 2>&1 || exit 0
+    restart
+    ;;
   *)
-    echo "Usage: {start|stop|status|restart}"
+    echo "Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status}"
     RETVAL=3
     ;;
 esac
+cd "$OLDPWD" || exit 1
 
-exit $RETVAL
+if [ "$RCSTATUS" ]; then
+  rc_exit
+fi
+
+exit "$RETVAL"
